{
	"version": 1740046730,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/redlightgreenlighthowto-sheet0.png",
		"images/redlightgreenlighthowto-sheet1.png",
		"images/play-sheet0.png",
		"images/bg-sheet0.png",
		"images/skateboard-sheet0.png",
		"images/rug-sheet0.png",
		"images/rug-sheet1.png",
		"images/manidle-sheet0.png",
		"images/sprite-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/flame-sheet0.png",
		"images/particles.png",
		"media/tap.m4a",
		"media/tap.ogg",
		"media/coin collect.m4a",
		"media/coin collect.ogg",
		"media/jump.m4a",
		"media/jump.ogg",
		"media/rugs and coins - cry.m4a",
		"media/rugs and coins - cry.ogg",
		"media/rugs and coins bgm.m4a",
		"media/rugs and coins bgm.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}